title: My personal experience
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  You will find some good stuff here

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
